name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate pngs
      uses: ./ # Uses an action in the root directory
      with:
        source_folder: "my_code_files"
        output_folder: "snaps"
        syntax_theme: "emacs"
